export const GPT4_API_URL = 'https://api.openai.com/v1/chat/completions';

export const DIETARY_RESTRICTIONS = [
  'Vegetarian',
  'Vegan',
  'Gluten-free',
  'None',
];

export const FITNESS_GOAL = ['Weight loss', 'Muscle gain', 'Maintenance'];

export const DESIRED_RATE_OF_PROGRESS = [
  'Slow',
  'Moderate',
  'Steady',
  'Aggressive',
];

export const ACTIVITY_LEVEL = [
  'Sedentary',
  'Lightly active',
  'Moderately active',
  'Very active',
];

export const EXERCISES = [
  'Bench Press',
  'Incline Bench Press',
  'Decline Bench Press',
  'Dumbbell Flyes',
  'Push-Ups',
  'Chest Dips',
  'Cable Crossovers',
  'Pull-Ups',
  'Lat Pulldowns',
  'Bent-Over Barbell Rows',
  'Dumbbell Rows',
  'T-Bar Rows',
  'Deadlifts',
  'Seated Cable Rows',
  'Military Press',
  'Dumbbell Shoulder Press',
  'Arnold Press',
  'Lateral Raises',
  'Front Raises',
  'Rear Delt Flyes',
  'Upright Rows',
  'Barbell Curls',
  'Dumbbell Curls',
  'Hammer Curls',
  'Preacher Curls',
  'Concentration Curls',
  'Cable Curls',
  'Tricep Dips',
  'Skull Crushers',
  'Tricep Pushdowns',
  'Overhead Tricep Extensions',
  'Close-Grip Bench Press',
  'Kickbacks',
  'Squats',
  'Leg Press',
  'Lunges',
  'Leg Curls',
  'Leg Extensions',
  'Calf Raises',
  'Crunches',
  'Planks',
  'Russian Twists',
  'Leg Raises',
  'Bicycle Crunches',
  'Mountain Climbers',
  'Running (Treadmill)',
  'Cycling (Stationary Bike)',
  'Rowing Machine',
  'Jump Rope',
  'Elliptical Trainer',
  'Stair Climber',
  'Burpees',
  'Kettlebell Swings',
  'Clean and Press',
  'Snatches',
  "Farmer's Walk",
];
